(load "graph-util")

(defparameter *nodes* '((1)
                        (2)
                        (3)
                        (4)
                        (5)
                        (6) 
                        (7) 
                        (8)))

(defparameter *shortest-edges* '((1 (2 11))
                        (2 (3 9) (4 14))
                        (3 (5 12) (6 14))
                        (4 (5 10) (6 11))
                        (5 (7 8))
                        (6 (7 10))
                        (7 (8 13))))

(defparameter *longest-edges* '((1 (2 14))
                        (2 (3 11) (4 18))
                        (3 (5 16) (6 15))
                        (4 (5 15) (6 17))
                        (5 (7 12))
                        (6 (7 13))
                        (7 (8 16))))

(graph->png "shortest-network" *nodes* *shortest-edges*)
(graph->png "longest-network" *nodes* *longest-edges*)
